tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            "colors": {
                "error": "#ba1a1a",
                "primary-container": "#d1451e",
                "on-secondary-fixed": "#281800",
                "background": "#faf9f6",
                "secondary": "#805600",
                "surface-container-high": "#e9e8e5",
                "tertiary-fixed": "#c6ebd9",
                "tertiary-container": "#5b7d6e",
                "on-surface": "#1a1c1a",
                "outline-variant": "#e2bfb6",
                "on-error-container": "#93000a",
                "on-tertiary": "#ffffff",
                "surface-container": "#efeeeb",
                "on-tertiary-fixed": "#002116",
                "secondary-fixed": "#ffddb0",
                "on-secondary": "#ffffff",
                "secondary-container": "#fcaf19",
                "surface-variant": "#e3e2e0",
                "error-container": "#ffdad6",
                "inverse-on-surface": "#f2f1ee",
                "surface-container-lowest": "#ffffff",
                "on-primary-container": "#fffeff",
                "on-secondary-container": "#694600",
                "surface-container-low": "#f4f3f1",
                "tertiary-fixed-dim": "#aacfbd",
                "surface-container-highest": "#e3e2e0",
                "on-primary-fixed-variant": "#881f00",
                "secondary-fixed-dim": "#ffba45",
                "on-background": "#1a1c1a",
                "on-primary-fixed": "#3c0800",
                "primary-fixed-dim": "#ffb5a1",
                "on-primary": "#ffffff",
                "surface-tint": "#b02e05",
                "surface-dim": "#dbdad7",
                "on-tertiary-fixed-variant": "#2c4d40",
                "inverse-surface": "#2f312f",
                "primary-fixed": "#ffdbd1",
                "tertiary": "#436456",
                "on-surface-variant": "#5a413a",
                "on-tertiary-container": "#fefffc",
                "inverse-primary": "#ffb5a1",
                "surface": "#faf9f6",
                "outline": "#8e7069",
                "on-secondary-fixed-variant": "#614000",
                "surface-bright": "#faf9f6",
                "primary": "#ae2d04",
                "on-error": "#ffffff",
                "recipe-accent": "#ae2d04",
                "recipe-warm": "#fcaf19",
                "recipe-surface": "#fffaf4",
                "recipe-text": "#5a413a"
            },
            "borderRadius": {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "0.75rem",
                "full": "9999px"
            },
            "spacing": {
                "unit": "4px",
                "margin": "32px",
                "gutter": "24px",
                "container-max": "1280px"
            },
            "fontFamily": {
                "body-lg": ["Plus Jakarta Sans"],
                "body-md": ["Plus Jakarta Sans"],
                "headline-md": ["Be Vietnam Pro"],
                "headline-lg": ["Be Vietnam Pro"],
                "headline-lg-mobile": ["Be Vietnam Pro"],
                "label-sm": ["Plus Jakarta Sans"]
            },
            "fontSize": {
                "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
                "body-md": ["16px", {"lineHeight": "1.5", "fontWeight": "400"}],
                "headline-md": ["24px", {"lineHeight": "1.3", "fontWeight": "600"}],
                "headline-lg": ["48px", {"lineHeight": "1.1", "fontWeight": "700"}],
                "headline-lg-mobile": ["32px", {"lineHeight": "1.2", "fontWeight": "700"}],
                "label-sm": ["12px", {"lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "600"}]
            }
        },
    },
};